Add `--api-key` CLI option
bluesky/tiled pull request #596
Opened 2023-10-31 13:56 UTC by danielballan

Closes #583 

e.g.

```
tiled serve catalog --temp --api-key=secret
```

Since there is only ever one key, I think a flag plus the existing env var (`TILED_SINGLE_USER_API_KEY`) is good enough for now. We can add `--api-key-file` later if we like.

2023-10-31 16:06 UTC, danielballan commented
FYI, unit testing these CLIs is a known issue, #518.

2023-11-15 15:34 UTC, padraic-shafer requested changes
Spotted one settings update that gets called multiple times in a for-loop.  I think it should get moved out of that loop.

The rest looks good.

2023-11-15 15:34 UTC, padraic-shafer commented on tiled/server/app.py
> +                settings.single_user_api_key_generated = False
Move this out of the for-loop above?

```suggestion
        if authentication.get("single_user_api_key") is not None:
            settings.single_user_api_key_generated = False
```

2023-11-16 05:19 UTC, padraic-shafer approved these changes
This is a helpful addition to the Tiled CLI

2023-11-16 05:19 UTC, merged