Thread-safety for the client Cache()
bluesky/tiled pull request #662
Opened 2024-02-21 16:50 UTC by canismarko

Based on a mattermost conversation. I wanted to use the Cache() from multiple threads so I could make an awaitable wrapper around the Tiled client. 

sqlite3 does support thread-safety if it's built into the underlying sqlite library. So this PR has the cache check if the sqlite3 library supports thread-safety, and if it does then allows writes from other threads.

https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety

Even still, I'm not sure how parallel writes get handled, so I also included a thread lock forcing parallel writes to wait until previous writes are done. Might be overkill but I don't have a way to check this easily so figured I'd err on the side of caution.

2024-02-21 18:58 UTC, padraic-shafer requested changes
Thanks for adding this functionality.  I've added a simple suggestion to use enumerated constant values to refer to the magic numbers of `sqlite3.threadsafety`.

2024-02-21 18:58 UTC, padraic-shafer commented on tiled/client/cache.py
> +        return is_main_thread or sqlite_is_safe
I'm not sure there is any guarantee about ordinality of the `threadsafety` value in `sqlite3`. It's probably safer and arguably clearer to use a named constant here.

```suggestion
        SERIALIZED = 3  # Could be defined in an enum elsewhere
        is_main_thread = threading.current_thread().ident == self._owner_thread
        sqlite_is_safe = sqlite3.threadsafety == SERIALIZED
        return is_main_thread or sqlite_is_safe
```

* https://docs.python.org/3/library/sqlite3.html#sqlite3.threadsafety
* https://github.com/python/cpython/blob/347acded845d07b70232cade8d576b6f0aaeb473/Modules/_sqlite/module.c#L521-L541

2024-02-21 18:58 UTC, padraic-shafer commented on tiled/_tests/test_client_cache.py
> +
See comment regarding `sqlite3.threadsafety` and comparing to a named constant/enum.

2024-02-21 19:56 UTC, canismarko commented
Thanks @padraic-shafer, makes sense. I went with a full IntEnum since we're using those values in at least two places.

2024-02-21 19:58 UTC, padraic-shafer approved these changes
👍
Thanks for adding those updates!  This looks great.

2024-02-22 13:51 UTC, danielballan commented
This demonstrates that, with this PR, we will cache (small) data responses. In `main`, we cannot because the request is made from a dask worker running on a different thread than the `Cache` and its SQLite connection were instantiated on.

```py
from tiled.client.cache import Cache
from tiled.client import from_profile

cache = Cache("main.db")
c = from_profile('demo', cache=cache)
c['generated']['tiny_image'][:]
```

```
$ sqlite3 main.db 'select cache_key, size from responses;'
https://tiled-demo.blueskyproject.io/api/v1/metadata/?include_data_sources=false|361
https://tiled-demo.blueskyproject.io/api/v1/metadata/generated?include_data_sources=false|397
https://tiled-demo.blueskyproject.io/api/v1/metadata/generated/tiny_image?include_data_sources=false|517
```

Now with this PR branch and the cache filename `pr_662.db`, notice the `/array/block/...` response cached.

```
$ sqlite3 pr_662.db 'select cache_key, size from responses;'
https://tiled-demo.blueskyproject.io/api/v1/metadata/?include_data_sources=false|361
https://tiled-demo.blueskyproject.io/api/v1/metadata/generated?include_data_sources=false|397
https://tiled-demo.blueskyproject.io/api/v1/metadata/generated/tiny_image?include_data_sources=false|517
https://tiled-demo.blueskyproject.io/api/v1/array/block/generated/tiny_image?block=0%2C0&expected_shape=50%2C50|20000
```

2024-02-22 13:51 UTC, danielballan approved these changes

2024-02-22 14:06 UTC, danielballan requested changes
Just before merging, I noticed a subtle issue. I have opened a PR into this PR branch for your review @canismarko https://github.com/spc-group/tiled/pull/1

2024-02-23 19:27 UTC, merged

2024-02-23 19:30 UTC, danielballan commented
Awesome! Thanks again @canismarko.